# Generated by Django 6.0.2 on 2026-02-17 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('iso', models.IntegerField()),
                ('format', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_development', models.DateField(blank=True, null=True)),
                ('date_scan', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('FINISHED', 'Terminée'), ('DEVELOPED', 'Développée'), ('SCANNED', 'Scannée')], default='IN_PROGRESS', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='equipment.camera')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='equipment.lens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
