# Generated by Django 6.0.2 on 2026-02-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('provider', models.CharField(choices=[('FLICKR', 'Flickr'), ('GOOGLE_PHOTOS', 'Google Photos'), ('GOOGLE_DRIVE', 'Google Drive'), ('SITE', 'Site personnel'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rolls.roll')),
            ],
        ),
    ]
