# Generated by Django 6.0.2 on 2026-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_urlphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
