# Generated by Django 6.0.2 on 2026-02-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('rolls', '0003_alter_roll_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='lens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='equipment.lens'),
        ),
    ]
