# Generated by Django 6.0.2 on 2026-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0004_alter_roll_lens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('FINISHED', 'Terminée'), ('DEVELOPED', 'Développée'), ('SCANNED', 'Scannée')], default='IN_PROGRESS', editable=False, max_length=20),
        ),
    ]
