# Generated by Django 6.0.2 on 2026-02-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='camera',
        ),
        migrations.AddField(
            model_name='lens',
            name='cameras',
            field=models.ManyToManyField(to='equipment.camera'),
        ),
    ]
